export const MAIN_SEARCH_LOADING = "MAIN_SEARCH_LOADING";
export const MAIN_SEARCH_SUCCESS = "MAIN_SEARCH_SUCCESS";
export const MAIN_SEARCH_FAILURE = "MAIN_SEARCH_FAILURE";
export const SET_MAIN_SEARCH_TYPE = "SET_MAIN_SEARCH_TYPE";
export const CLEAR_MAIN_SEARCH = "CLEAR_MAIN_SEARCH";
export const SET_MAIN_SEARCH_FILTER = "SET_MAIN_SEARCH_FILTER";
export const CLEAR_MAIN_SEARCH_FILTERS = "CLEAR_MAIN_SEARCH_FILTERS";
export const RESET_MAIN_SEARCH = " RESET_MAIN_SEARCH";
