export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";
export const PROFILE_RETRIEVED = "PROFILE_RETRIEVED";
export const BOOKMARKS_LOADING = "BOOKMARKS_LOADING";
export const BOOKMARKS_SUCCESS = "BOOKMARKS_SUCCESS";
export const BOOKMARKS_FAILURE = "BOOKMARKS_FAILURE";
export const REVIEWS_LOADING = "REVIEWS_LOADING";
export const REVIEWS_SUCCESS = "REVIEWS_SUCCESS";
export const REVIEWS_FAILURE = "REVIEWS_FAILURE";
