export const SET_BOOKMARKS_SEARCH_TYPE = "SET_BOOKMARKS_SEARCH_TYPE";
export const CLEAR_BOOKMARKS_SEARCH = "CLEAR_BOOKMARKS_SEARCH";
export const RESET_BOOKMARKS_SEARCH = "RESET_BOOKMARKS_SEARCH";
export const SAVE_BOOKMARKS_SEARCH_INPUT = "SAVE_BOOKMARKS_SEARCH_INPUT";
