export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAIL";
export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const SET_SEARCH_FILTER = "SET_SEARCH_FILTER";
export const CLEAR_SEARCH_FILTERS = "CLEAR_SEARCH_FILTERS";
