export const HERO_SEARCH_ONE_LOADING = "HERO_SEARCH_ONE_LOADING";
export const HERO_SEARCH_ONE_SUCCESS = "HERO_SEARCH_ONE_SUCCESS";
export const HERO_SEARCH_ONE_FAILURE = "HERO_SEARCH_ONE_FAILURE";
export const SET_HERO_SEARCH_ONE_TYPE = "SET_HERO_SEARCH_ONE_TYPE";
export const CLEAR_HERO_SEARCH_ONE = "CLEAR_HERO_SEARCH_ONE";
export const SET_HERO_SEARCH_ONE_FILTER = "SET_HERO_SEARCH_ONE_FILTER";
export const CLEAR_HERO_SEARCH_ONE_FILTERS = "CLEAR_HERO_SEARCH_ONE_FILTERS";
export const RESET_SEARCH_ONE = " RESET_SEARCH_ONE";
