export const CLEAR_PROFESSOR_REVIEWS = "CLEAR_PROFESSOR_REVIEWS";
export const PROFESSOR_REVIEWS_LOADING = "PROFESSOR_REVIEWS_LOADING";
export const PROFESSOR_REVIEWS_SUCCESS = "PROFESSOR_REVIEWS_SUCCESS";
export const PROFESSOR_REVIEWS_FAILURE = "PROFESSOR_REVIEWS_FAILURE";
